#
# Makefile for the touchscreen drivers.
#
obj-$(CONFIG_TOUCHSCREEN_FT5X06)	+= ft5x06_ts.o
obj-$(CONFIG_TOUCHSCREEN_FT5X06_I2C)    += ft5x06_ts_i2c.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX)		+= gt9xx/
obj-$(CONFIG_TOUCHSCREEN_IST30XX)	+= imagis/

obj-$(CONFIG_TOUCHSCREEN_SWEEP2WAKE)	+= sweep2wake.o

