#!/bin/bash

echo "****Очистка старых конфигов****"
export ARCH=arm

export CROSS_COMPILE=~/cm13/prebuilts/gcc/linux-x86/arm/arm-cortex-linux-gnueabi-linaro_5.2/bin/arm-cortex-linux-gnueabi-
export EABI_PATCH=~/cm13/prebuilts/gcc/linux-x86/arm/arm-cortex-linux-gnueabi-linaro_5.2/bin

#export CROSS_COMPILE=~/cm13/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin/arm-linux-androideabi-
#export EABI_PATCH=~/cm13/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin

export KERNELRELEASE=3.4.0
make clean && make mrproper

echo "****Сборка ядра****"
make cyanogenmod_armani_defconfig
make -j5
echo "****Готово****"

