# Makefile for staging directory

# fix for build system bug...
obj-$(CONFIG_STAGING)		+= staging.o

obj-$(CONFIG_ANDROID)		+= android/
obj-$(CONFIG_PRIMA_WLAN)	+= prima/
obj-$(CONFIG_PRONTO_WLAN)	+= prima/
